/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'rank' : IDL.Nat,
  'wins' : IDL.Nat,
  'bestScore' : IDL.Nat,
  'level' : IDL.Nat,
});
export const Player = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'gamesPlayed' : IDL.Nat,
  'playerId' : IDL.Principal,
  'coins' : IDL.Nat,
  'wins' : IDL.Nat,
  'bestScore' : IDL.Nat,
  'recentScores' : IDL.Vec(IDL.Nat),
});
export const PlayerStats = IDL.Record({
  'xp' : IDL.Nat,
  'gamesPlayed' : IDL.Nat,
  'coins' : IDL.Nat,
  'wins' : IDL.Nat,
  'bestScore' : IDL.Nat,
  'level' : IDL.Nat,
  'recentScores' : IDL.Vec(IDL.Nat),
});
export const GameResult = IDL.Record({ 'won' : IDL.Bool, 'score' : IDL.Nat });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getOwnLevel' : IDL.Func([], [IDL.Nat], ['query']),
  'getOwnProfile' : IDL.Func([], [Player], ['query']),
  'getOwnWinRatePercentage' : IDL.Func([], [IDL.Nat], ['query']),
  'getPlayerProfile' : IDL.Func([IDL.Principal], [Player], ['query']),
  'getPlayerStats' : IDL.Func([], [PlayerStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerOrUpdateProfile' : IDL.Func([IDL.Text], [], []),
  'submitGameResult' : IDL.Func([GameResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'rank' : IDL.Nat,
    'wins' : IDL.Nat,
    'bestScore' : IDL.Nat,
    'level' : IDL.Nat,
  });
  const Player = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'playerId' : IDL.Principal,
    'coins' : IDL.Nat,
    'wins' : IDL.Nat,
    'bestScore' : IDL.Nat,
    'recentScores' : IDL.Vec(IDL.Nat),
  });
  const PlayerStats = IDL.Record({
    'xp' : IDL.Nat,
    'gamesPlayed' : IDL.Nat,
    'coins' : IDL.Nat,
    'wins' : IDL.Nat,
    'bestScore' : IDL.Nat,
    'level' : IDL.Nat,
    'recentScores' : IDL.Vec(IDL.Nat),
  });
  const GameResult = IDL.Record({ 'won' : IDL.Bool, 'score' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getOwnLevel' : IDL.Func([], [IDL.Nat], ['query']),
    'getOwnProfile' : IDL.Func([], [Player], ['query']),
    'getOwnWinRatePercentage' : IDL.Func([], [IDL.Nat], ['query']),
    'getPlayerProfile' : IDL.Func([IDL.Principal], [Player], ['query']),
    'getPlayerStats' : IDL.Func([], [PlayerStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerOrUpdateProfile' : IDL.Func([IDL.Text], [], []),
    'submitGameResult' : IDL.Func([GameResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };