/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameResult { 'won' : boolean, 'score' : bigint }
export interface LeaderboardEntry {
  'username' : string,
  'rank' : bigint,
  'wins' : bigint,
  'bestScore' : bigint,
  'level' : bigint,
}
export interface Player {
  'xp' : bigint,
  'username' : string,
  'gamesPlayed' : bigint,
  'playerId' : Principal,
  'coins' : bigint,
  'wins' : bigint,
  'bestScore' : bigint,
  'recentScores' : Array<bigint>,
}
export interface PlayerStats {
  'xp' : bigint,
  'gamesPlayed' : bigint,
  'coins' : bigint,
  'wins' : bigint,
  'bestScore' : bigint,
  'level' : bigint,
  'recentScores' : Array<bigint>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getOwnLevel' : ActorMethod<[], bigint>,
  'getOwnProfile' : ActorMethod<[], Player>,
  'getOwnWinRatePercentage' : ActorMethod<[], bigint>,
  'getPlayerProfile' : ActorMethod<[Principal], Player>,
  'getPlayerStats' : ActorMethod<[], PlayerStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerOrUpdateProfile' : ActorMethod<[string], undefined>,
  'submitGameResult' : ActorMethod<[GameResult], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];